backend:
  name: github
  repo: camberwellshowtime/website # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: uploads # Folder where user uploaded files should go

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "data"
    label: "Data"
    editor:
      preview: false
    files:
      - name: "performances"
        label: "Performances"
        file: "_data/performances.yml"
        fields:
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Description", name: "description", widget: "text"}
      - name: "cast"
        label: "Cast"
        file: "_data/cast.yml"
        fields:
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Date", name: "date", widget: "text"}
